name: 'Fortu Refresh Charts'
description: 'Refresh helm chart until not found.'
inputs:
  token:
    description: 'Token'
    required: true
  chart:
    description: 'Chart'
    required: true
  version:
    description: 'Version'
    required: true
runs:
  using: "composite"
  steps:
    - run: 
        TOKEN=${{ inputs.token }}
        CHART=$(echo ${{ inputs.chart }} | sed 's/\"//g')
        VERSION=${{ inputs.version }}
        ${{ github.action_path }}/start.sh
      shell: bash